### ISSUE TITLE
IMPORTANT :P

### ISSUE THREAD

**Issue by tshradheya** [CS2103JAN2018-W10-B4/main#57]
Hey guys, 

Just one quick thing that you guys need to do.

- [x] Update UG with details of features that you dont plan to do and will do in V2.0[ Give very brief detail on what you think the feature does]
e.g.
``` 
10.1. Search Command [Coming in 2.0]
Users will be able to search for persons fulfilling all keywords provided by the users.
This allow a more focused and efficient search for users.
Format: search KEYWORD [MORE KEYWORDS]
KEYWORD is either n/PHONE or t/TAG
```

- [x] According to your major and minor features, update UG with those features and when you plan to do it 
e.g.
``` 
7.20. Deleting a reminder: deletereminder[Proposed to finish in V1.4]
Deletes a specified reminder from iContacts.
Format: deletereminder INDEX

Deletes the reminder at the specified INDEX.

The index refers to the index number shown in the list of reminders.

The index must be a positive integer 1, 2, 3, …
```

- [x] For the features already implemented, add complete details for it so that even for someone who doesn't know your product and give relevant examples on how to use the feature. [maybe add screenshots]

P.S. I will be using your team's issue tracker to communicate, so each of you please react to this post with any emoji so that I know you have read it. Feel free to ask any questions of you have any doubts

**Comment by ng95junwei** [comment]
:)

**Comment by jlks96** [comment]
👍

**Comment by jlks96** [comment]
BTW @tshradheya do you know how to remove an issue (coz i accidentally make reference from by minor enhancement story to the epic, and cant really dereference) see issue 11

**Comment by tshradheya** [comment]
Its impossible to remove an issue, all you can do is edit the issue to make it something else and remove any reference from it. And add a new issue of whatever you want.

Its fine to have some unrelated references, but try to minimize them by editing the unrelated issues

**Comment by jlks96** [comment]
How can I remove reference from an issue?

**Comment by tshradheya** [comment]
It may be impossible to remove references as well.

If you want to do it cleanly, label the old issues as invalid and make new issues for the epic and stories and reference them correctly.

**Comment by jlks96** [comment]
ok thanks

**Comment by jlks96** [comment]
@tshradheya Just to clarify, for the jar for v1.3, how do we release it on github?

**Comment by tshradheya** [comment]
![screenshot_2018-03-27-18-46-29-920_com android chrome](https://user-images.githubusercontent.com/12574756/37962923-4d36aefe-31ef-11e8-93b7-99300266b5d7.png)

Click kn the ` Selecting them` part in blue on the `Attach the Binarie`s and upload your jar file

**Comment by jlks96** [comment]
So we just need to attach the jar file in the release right

**Comment by tshradheya** [comment]
Yes :)

**Comment by jlks96** [comment]
Noted. Thanks!

**Comment by jlks96** [comment]
@tshradheya I keeping getting error when running the jar file, any idea why?
![image](https://user-images.githubusercontent.com/31044037/37985674-0535960a-322c-11e8-879e-2e3f2ece0690.png)

**Comment by jlks96** [comment]
Is it because of Java 9?

**Comment by tshradheya** [comment]
Sorry missed this https://github.com/CS2103JAN2018-W10-B4/main/issues/57#issuecomment-376619449
Although I think you have already resolved it

Closing issue

**Comment by jlks96** [comment]
@tshradheya do you know what the project demonstrated in Lecture 1 is? I think I am using the same library (CalendarFX) as them and wish to have a look at their implementation for reference.

**Comment by tshradheya** [comment]
Not really sure.
I havent seen that project
